### ISSUE TITLE
网站上的 Scaling Law 无法正确加载

### ISSUE THREAD

**Issue by ofou** [luhengshiwo/LLMForEverybody#38]
网站上的 [所有人都谈的 Scaling Law 是什么](https://luhengshiwo.github.io/LLMForEverybody) 无法正确加载。问题似乎是网站上的链接指向 `.md`，而不是像其他链接那样指向 `.html`。

**Comment by luhengshiwo** [comment]
谢谢你的反馈，这个问题似乎是因为名称中出现了空格导致的，我现在先修复了下。
